### ISSUE TITLE
TV is ON as "AND" condition

### ISSUE THREAD

**Issue by Tjadevisser** [MaxvandeLaar/homey-webos-plus#12]
Please add the TV is ON/OFF as "and" condition.

My lights in the livingroom go off after 10 minutes except when te TV is on (sitting still on the couch).
Condition is available in original athom app, missing in this (almost) perfect fork..

Keep up the good work.

**Comment by MaxvandeLaar** [comment]
Is this not what you are looking for? The condition for the tv is it's on or off? This is already implemented.

<img width="388" alt="image" src="https://user-images.githubusercontent.com/5842932/77426007-ec683200-6dd3-11ea-9004-f58749fb7c74.png">

If this is not what you are looking for then I please elaborate what you are missing in the current version?

**Comment by Tjadevisser** [comment]
Schele kip:).
Thanks.

**Comment by MaxvandeLaar** [comment]
No problem 🙂
