### ISSUE TITLE
TV turns on when Of command is send

### ISSUE THREAD

**Issue by kaohlive** [MaxvandeLaar/homey-webos-plus#14]
When the TV is off and an Off command is send from a flow the device turns on.

**Comment by MaxvandeLaar** [comment]
@kaohlive, is the command executed as well, or did it only turned the tv on? 

Whenever a command is executed, I check if there is a connection with the tv, if not I try to connect. I think this is what you are experiencing. Luckily, I am well on my way with the rewrite so I need to check if this is still happening with the new method.

**Comment by kaohlive** [comment]
it only turns on the tv, else i would not have noticed 😂. but lets await your rewrite.

**Comment by MaxvandeLaar** [comment]
@kaohlive

I think this is fixed in V2.0.0-rc1

**Comment by kaohlive** [comment]
I think so to.
