### ISSUE TITLE
WebOS Plus v1.3.1 crashing

### ISSUE THREAD

**Issue by shaarkys** [MaxvandeLaar/homey-webos-plus#19]
**Describe the bug**
WebOS Plus v1.3.1 crashing upon start / app restart - not working at all

**To Reproduce**
Happens after I have added device / LG OS TV

**Screenshots**

![obrazek](https://user-images.githubusercontent.com/14859895/77819361-93054900-70da-11ea-9ca8-ae3f584d883b.png)

**Comment by shaarkys** [comment]
Seems it's working with 2.0 rc, sorry ;-)

https://github.com/MaxvandeLaar/homey-webos-plus/releases/tag/v2.0.0-rc2

**Comment by MaxvandeLaar** [comment]
@shaarkys, v2.x doesn't really 'fix' it, check #4
