### ISSUE TITLE
SDK 3

### ISSUE THREAD

**Issue by robindelange** [MaxvandeLaar/homey-webos-plus#48]
Hallo Max, 

ben je toevallig van plan de Webos plus app naar SDK3 te updaten? zodat hij ook op de nieuwe Homey pro gebruikt kan worden?
tevens valt het me op dat de app niet constanteert dat er iets aan het afspelen is, wel ziet de app dat de tv aan en uit gaat. ik zou graag namelijk een bioscoop scene van mijn lampen willen aansturen als netflix begint af te spelen

groeten 

Robin de Lange

**Comment by MaxvandeLaar** [comment]
Hi Robin, 

Ik heb het nieuws omtrent nieuwe Homey devices en updates niet echt meer gevolgd. Werkt SDK2 niet meer dan? Reden waarom ik niet direct geupgrade heb naar SDK3 is vanwege een groot aantal gebruikers nog geen SDK3 kon draaien. Uiteraard is dat al een hele tijd geleden en dit speelt natuurlijk niet meer. Maw. ik zal eens kijken hoeveel werk het is om dit te upgraden. 

Het is inderdaad zo dat de app niet kan zien wat je afspeelt. Wel is het mogelijk flows te maken op basis van triggers naar andere TV apps zoals Live TV/Disney/Netflix/etc. en tijdens een 'als' kaart te checken welke app op dit moment open is. Helaas ondersteunt de gebruikte API niet de usecase zoals je omschrijft. Ik heb geen flauw idee wanneer Netflix bijv. wel of niet iets afspeelt. Alleen of deze geopend is.

Gr. Max

**Comment by robindelange** [comment]
Max,

Bedankt voor je snelle reactie.

De nieuwe homey kan alleen maar SDK3 apps aan, nu is er op het forum al een bericht waarin sdk2 apps staan en wordt er veel meegedacht en geholpen om meer als de updaten naar sdk3. Sommige apps zijn zelfs al van developer gewisseld om zo toch te updaten. (Als ik Athom mag geloven, is het van sdk2 naar sdk3 updaten niet veel werk. Dit hebben zei gezegd in een youtube video over vragen over de nieuwe homey pro. Echter ben ik geen programmeur dus weet dat uiteraard niet zeker)

In het forum zijn al meerdere mensen die gebruik maken van jou lg app en zouden deze graag ook geupdate willen zien worden.😁

Over het het herkennen van afspelen is er wel een “EN” kaart echter als ik bijvoorbeeld een flow maak met

ALS : de tv is aangegaan
EN :  tv is aan het afspelen.
DAN: start bioscoop (mijn lampen op bepaalde dimwaardes

Hierbij ziet hij keurig dat de tv aan of uit gaat echter het afspelen ziet hij niet, een app herkent hij we bij verwisselen maar doe je bijvoorbeeld de tv uit met neflix erop en iets later zet je de tv weer aan dan komt netflix er weer automatisch voor. Nu detecteert de tv dus geen verandering in app waardoor dit kaartje dus niet gebruikt kan worden in mijn flow waarbij ik dingen aan wil sturen op basis van het afspelen van mijn tv.

Als ik de tv aanzet via de app en netflix komt ervoor en druk op de play knop in de app op homey dan werkt het wel en gaat de tv ook daadwerkelijk spelen.

Het lijkt er dus op dat als je de tv met de afstandbediening bedient dat de app alleen het aan en uit ziet, niet of je op afspelen hebt gedrukt. Dus de terugkoppeling werkt dan niet

Hoop dat ik het beetje begrijpelijk gemaakt heb en dat je wellicht hierin iets voor mij kunt betekeken.

Alvast bedankt namens mij en de lg app gebruikers welke deze app ook graag op de nieuwe homey willen gebruiken💪🏻

Met vriendelijke groet,

Robin de Lange
[image0.png]

Op 7 nov. 2022 om 09:13 heeft Max ***@***.***> het volgende geschreven:

﻿

Hi Robin,

Ik heb het nieuws omtrent nieuwe Homey devices en updates niet echt meer gevolgd. Werkt SDK2 niet meer dan? Reden waarom ik niet direct geupgrade heb naar SDK3 is vanwege een groot aantal gebruikers nog geen SDK3 kon draaien. Uiteraard is dat al een hele tijd geleden en dit speelt natuurlijk niet meer. Maw. ik zal eens kijken hoeveel werk het is om dit te upgraden.

Het is inderdaad zo dat de app niet kan zien wat je afspeelt. Wel is het mogelijk flows te maken op basis van triggers naar andere TV apps zoals Live TV/Disney/Netflix/etc. en tijdens een 'als' kaart te checken welke app op dit moment open is. Helaas ondersteunt de gebruikte API niet de usecase zoals je omschrijft. Ik heb geen flauw idee wanneer Netflix bijv. wel of niet iets afspeelt. Alleen of deze geopend is.

Gr. Max

**Comment by robindelange** [comment]
Max, 

al enige idee of de app naar SDK3 geschreven kan worden?

met vriendelijke groet, 

Robin de Lange

**Comment by MaxvandeLaar** [comment]
Hi Robin, 

Ik ben toevallig vorige week begonnen met de migratie. Het blijkt iets meer werk te zijn dan ik had verwacht. Maar dus work in progress.

Gr. Max

**Comment by robindelange** [comment]
Goedemiddag Max,

Aah dat is super om te horen! Bedankt nogmaals.

Met vriendelijke groet,

Robin de Lange

Op 12 jan. 2023, om 16:09 heeft Max ***@***.******@***.***>> het volgende geschreven:



Hi Robin,

Ik ben toevallig vorige week begonnen met de migratie. Het blijkt iets meer werk te zijn dan ik had verwacht. Maar dus work in progress.

Gr. Max

**Comment by dennisbekker** [comment]
Echt fijn dat je de tijd wilt nemen om dit te doen, dank je wel! ik gebruik deze app al zo lang en nog nooit issues gehad.

**Comment by DieJan** [comment]
Hoi Max, is er al een update over de overgang naar SDK3? Zou echt top zijn! 😄

**Comment by DominicVonk** [comment]
PR #56

**Comment by MaxvandeLaar** [comment]
SDK3 version is released with the help of @DominicVonk! Thanks all.
