### ISSUE TITLE
Image on LG C2 TV

### ISSUE THREAD

**Issue by jesper-domotica** [MaxvandeLaar/homey-webos-plus#61]
When i want to send a Message to TV, the image will not show. For example i have a flow when my doorbell rings, it takes a snapshot from ring with image grabber.

And another flow: When image grabber has recieved a new image. Then send a message to TV, i tried a toast message with url and a toast message from galary. In both ways i only see the text message So the flow work but i dont see the image. Tried more extentions. But thougt the normal jpg would work.

**Comment by MaxvandeLaar** [comment]
@jesper-domotica sadly, not all TVs support toasts/alerts with images. Not much I can do about it as far as I am aware 😔

**Comment by MaxvandeLaar** [comment]
I think you already have 🫠. If you are sending a toast to the tv via the flow with an image, and there is no image, it is not supported. 

In all seriousness, I don't know how to check. I just know some TVs display the image while others don't 😔
